///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HotelDetailModelHotelWildcardsHotelRoomDescription {
/*
{
  "content": "MONOPARENTAL 1 ADULT 1 CHILD"
} 
*/

  String content;

  HotelDetailModelHotelWildcardsHotelRoomDescription({
    this.content,
  });
  HotelDetailModelHotelWildcardsHotelRoomDescription.fromJson(
      Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelWildcards {
/*
{
  "roomType": "DBT.ST-2",
  "roomCode": "DBT",
  "characteristicCode": "ST-2",
  "hotelRoomDescription": {
    "content": "MONOPARENTAL 1 ADULT 1 CHILD"
  }
} 
*/

  String roomType;
  String roomCode;
  String characteristicCode;
  HotelDetailModelHotelWildcardsHotelRoomDescription hotelRoomDescription;

  HotelDetailModelHotelWildcards({
    this.roomType,
    this.roomCode,
    this.characteristicCode,
    this.hotelRoomDescription,
  });
  HotelDetailModelHotelWildcards.fromJson(Map<String, dynamic> json) {
    roomType = json['roomType']?.toString();
    roomCode = json['roomCode']?.toString();
    characteristicCode = json['characteristicCode']?.toString();
    hotelRoomDescription = (json['hotelRoomDescription'] != null)
        ? HotelDetailModelHotelWildcardsHotelRoomDescription.fromJson(
            json['hotelRoomDescription'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['roomType'] = roomType;
    data['roomCode'] = roomCode;
    data['characteristicCode'] = characteristicCode;
    if (hotelRoomDescription != null) {
      data['hotelRoomDescription'] = hotelRoomDescription.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelImagesTypeDescription {
/*
{
  "content": "Restaurant"
} 
*/

  String content;

  HotelDetailModelHotelImagesTypeDescription({
    this.content,
  });
  HotelDetailModelHotelImagesTypeDescription.fromJson(
      Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelImagesType {
/*
{
  "code": "RES",
  "description": {
    "content": "Restaurant"
  }
} 
*/

  String code;
  HotelDetailModelHotelImagesTypeDescription description;

  HotelDetailModelHotelImagesType({
    this.code,
    this.description,
  });
  HotelDetailModelHotelImagesType.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    description = (json['description'] != null)
        ? HotelDetailModelHotelImagesTypeDescription.fromJson(
            json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelImages {
/*
{
  "type": {
    "code": "RES",
    "description": {
      "content": "Restaurant"
    }
  },
  "path": "00/000001/000001a_hb_r_001.jpg",
  "order": 1,
  "visualOrder": 603
} 
*/

  HotelDetailModelHotelImagesType type;
  String path;
  int order;
  int visualOrder;

  HotelDetailModelHotelImages({
    this.type,
    this.path,
    this.order,
    this.visualOrder,
  });
  HotelDetailModelHotelImages.fromJson(Map<String, dynamic> json) {
    type = (json['type'] != null)
        ? HotelDetailModelHotelImagesType.fromJson(json['type'])
        : null;
    path = json['path']?.toString();
    order = json['order']?.toInt();
    visualOrder = json['visualOrder']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (type != null) {
      data['type'] = type.toJson();
    }
    data['path'] = path;
    data['order'] = order;
    data['visualOrder'] = visualOrder;
    return data;
  }
}

class HotelDetailModelHotelInterestPoints {
/*
{
  "facilityCode": 40,
  "facilityGroupCode": 100,
  "order": 1,
  "poiName": "Barcelona",
  "distance": "100000"
} 
*/

  int facilityCode;
  int facilityGroupCode;
  int order;
  String poiName;
  String distance;

  HotelDetailModelHotelInterestPoints({
    this.facilityCode,
    this.facilityGroupCode,
    this.order,
    this.poiName,
    this.distance,
  });
  HotelDetailModelHotelInterestPoints.fromJson(Map<String, dynamic> json) {
    facilityCode = json['facilityCode']?.toInt();
    facilityGroupCode = json['facilityGroupCode']?.toInt();
    order = json['order']?.toInt();
    poiName = json['poiName']?.toString();
    distance = json['distance']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['facilityCode'] = facilityCode;
    data['facilityGroupCode'] = facilityGroupCode;
    data['order'] = order;
    data['poiName'] = poiName;
    data['distance'] = distance;
    return data;
  }
}

class HotelDetailModelHotelIssuesDescription {
/*
{
  "content": "As a result of local government measures and guidelines put in place by services providers – including hotels and ancillaries – guests may find that some facilities or services are not available.Please visit https://static-sources.s3-eu-west-1.amazonaws.com/policy/index.html for further information"
} 
*/

  String content;

  HotelDetailModelHotelIssuesDescription({
    this.content,
  });
  HotelDetailModelHotelIssuesDescription.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelIssues {
/*
{
  "issueCode": "COVID",
  "issueType": "COVID",
  "description": {
    "content": "As a result of local government measures and guidelines put in place by services providers – including hotels and ancillaries – guests may find that some facilities or services are not available.Please visit https://static-sources.s3-eu-west-1.amazonaws.com/policy/index.html for further information"
  },
  "dateFrom": "2020-05-15",
  "dateTo": "2021-12-31",
  "order": 1,
  "alternative": false
} 
*/

  String issueCode;
  String issueType;
  HotelDetailModelHotelIssuesDescription description;
  String dateFrom;
  String dateTo;
  int order;
  bool alternative;

  HotelDetailModelHotelIssues({
    this.issueCode,
    this.issueType,
    this.description,
    this.dateFrom,
    this.dateTo,
    this.order,
    this.alternative,
  });
  HotelDetailModelHotelIssues.fromJson(Map<String, dynamic> json) {
    issueCode = json['issueCode']?.toString();
    issueType = json['issueType']?.toString();
    description = (json['description'] != null)
        ? HotelDetailModelHotelIssuesDescription.fromJson(json['description'])
        : null;
    dateFrom = json['dateFrom']?.toString();
    dateTo = json['dateTo']?.toString();
    order = json['order']?.toInt();
    alternative = json['alternative'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['issueCode'] = issueCode;
    data['issueType'] = issueType;
    if (description != null) {
      data['description'] = description.toJson();
    }
    data['dateFrom'] = dateFrom;
    data['dateTo'] = dateTo;
    data['order'] = order;
    data['alternative'] = alternative;
    return data;
  }
}

class HotelDetailModelHotelTerminalsDescription {
/*
{
  "content": "Airport"
} 
*/

  String content;

  HotelDetailModelHotelTerminalsDescription({
    this.content,
  });
  HotelDetailModelHotelTerminalsDescription.fromJson(
      Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelTerminalsName {
/*
{
  "content": "Tarragona, Reus Airport"
} 
*/

  String content;

  HotelDetailModelHotelTerminalsName({
    this.content,
  });
  HotelDetailModelHotelTerminalsName.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelTerminals {
/*
{
  "terminalCode": "REU",
  "terminalType": "A",
  "distance": 15,
  "name": {
    "content": "Tarragona, Reus Airport"
  },
  "description": {
    "content": "Airport"
  }
} 
*/

  String terminalCode;
  String terminalType;
  int distance;
  HotelDetailModelHotelTerminalsName name;
  HotelDetailModelHotelTerminalsDescription description;

  HotelDetailModelHotelTerminals({
    this.terminalCode,
    this.terminalType,
    this.distance,
    this.name,
    this.description,
  });
  HotelDetailModelHotelTerminals.fromJson(Map<String, dynamic> json) {
    terminalCode = json['terminalCode']?.toString();
    terminalType = json['terminalType']?.toString();
    distance = json['distance']?.toInt();
    name = (json['name'] != null)
        ? HotelDetailModelHotelTerminalsName.fromJson(json['name'])
        : null;
    description = (json['description'] != null)
        ? HotelDetailModelHotelTerminalsDescription.fromJson(
            json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['terminalCode'] = terminalCode;
    data['terminalType'] = terminalType;
    data['distance'] = distance;
    if (name != null) {
      data['name'] = name.toJson();
    }
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelFacilitiesDescription {
/*
{
  "content": "Total number of rooms"
} 
*/

  String content;

  HotelDetailModelHotelFacilitiesDescription({
    this.content,
  });
  HotelDetailModelHotelFacilitiesDescription.fromJson(
      Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelFacilities {
/*
{
  "facilityCode": 70,
  "facilityGroupCode": 10,
  "description": {
    "content": "Total number of rooms"
  },
  "order": 1,
  "indYesOrNo": false,
  "number": 260,
  "voucher": false
} 
*/

  int facilityCode;
  int facilityGroupCode;
  HotelDetailModelHotelFacilitiesDescription description;
  int order;
  bool indYesOrNo;
  int number;
  bool voucher;

  HotelDetailModelHotelFacilities({
    this.facilityCode,
    this.facilityGroupCode,
    this.description,
    this.order,
    this.indYesOrNo,
    this.number,
    this.voucher,
  });
  HotelDetailModelHotelFacilities.fromJson(Map<String, dynamic> json) {
    facilityCode = json['facilityCode']?.toInt();
    facilityGroupCode = json['facilityGroupCode']?.toInt();
    description = (json['description'] != null)
        ? HotelDetailModelHotelFacilitiesDescription.fromJson(
            json['description'])
        : null;
    order = json['order']?.toInt();
    indYesOrNo = json['indYesOrNo'];
    number = json['number']?.toInt();
    voucher = json['voucher'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['facilityCode'] = facilityCode;
    data['facilityGroupCode'] = facilityGroupCode;
    if (description != null) {
      data['description'] = description.toJson();
    }
    data['order'] = order;
    data['indYesOrNo'] = indYesOrNo;
    data['number'] = number;
    data['voucher'] = voucher;
    return data;
  }
}

class HotelDetailModelHotelRoomsCharacteristicDescription {
/*
{
  "content": "CAPACITY 4"
} 
*/

  String content;

  HotelDetailModelHotelRoomsCharacteristicDescription({
    this.content,
  });
  HotelDetailModelHotelRoomsCharacteristicDescription.fromJson(
      Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelRoomsCharacteristic {
/*
{
  "code": "C4-1",
  "description": {
    "content": "CAPACITY 4"
  }
} 
*/

  String code;
  HotelDetailModelHotelRoomsCharacteristicDescription description;

  HotelDetailModelHotelRoomsCharacteristic({
    this.code,
    this.description,
  });
  HotelDetailModelHotelRoomsCharacteristic.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    description = (json['description'] != null)
        ? HotelDetailModelHotelRoomsCharacteristicDescription.fromJson(
            json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelRoomsTypeDescription {
/*
{
  "content": "DOUBLE"
} 
*/

  String content;

  HotelDetailModelHotelRoomsTypeDescription({
    this.content,
  });
  HotelDetailModelHotelRoomsTypeDescription.fromJson(
      Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelRoomsType {
/*
{
  "code": "DBL",
  "description": {
    "content": "DOUBLE"
  }
} 
*/

  String code;
  HotelDetailModelHotelRoomsTypeDescription description;

  HotelDetailModelHotelRoomsType({
    this.code,
    this.description,
  });
  HotelDetailModelHotelRoomsType.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    description = (json['description'] != null)
        ? HotelDetailModelHotelRoomsTypeDescription.fromJson(
            json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelRooms {
/*
{
  "roomCode": "DBL.C4-1",
  "isParentRoom": false,
  "minPax": 1,
  "maxPax": 5,
  "maxAdults": 4,
  "maxChildren": 4,
  "minAdults": 1,
  "description": "DOUBLE CAPACITY 4",
  "type": {
    "code": "DBL",
    "description": {
      "content": "DOUBLE"
    }
  },
  "characteristic": {
    "code": "C4-1",
    "description": {
      "content": "CAPACITY 4"
    }
  }
} 
*/

  String roomCode;
  bool isParentRoom;
  int minPax;
  int maxPax;
  int maxAdults;
  int maxChildren;
  int minAdults;
  String description;
  HotelDetailModelHotelRoomsType type;
  HotelDetailModelHotelRoomsCharacteristic characteristic;

  HotelDetailModelHotelRooms({
    this.roomCode,
    this.isParentRoom,
    this.minPax,
    this.maxPax,
    this.maxAdults,
    this.maxChildren,
    this.minAdults,
    this.description,
    this.type,
    this.characteristic,
  });
  HotelDetailModelHotelRooms.fromJson(Map<String, dynamic> json) {
    roomCode = json['roomCode']?.toString();
    isParentRoom = json['isParentRoom'];
    minPax = json['minPax']?.toInt();
    maxPax = json['maxPax']?.toInt();
    maxAdults = json['maxAdults']?.toInt();
    maxChildren = json['maxChildren']?.toInt();
    minAdults = json['minAdults']?.toInt();
    description = json['description']?.toString();
    type = (json['type'] != null)
        ? HotelDetailModelHotelRoomsType.fromJson(json['type'])
        : null;
    characteristic = (json['characteristic'] != null)
        ? HotelDetailModelHotelRoomsCharacteristic.fromJson(
            json['characteristic'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['roomCode'] = roomCode;
    data['isParentRoom'] = isParentRoom;
    data['minPax'] = minPax;
    data['maxPax'] = maxPax;
    data['maxAdults'] = maxAdults;
    data['maxChildren'] = maxChildren;
    data['minAdults'] = minAdults;
    data['description'] = description;
    if (type != null) {
      data['type'] = type.toJson();
    }
    if (characteristic != null) {
      data['characteristic'] = characteristic.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelPhones {
/*
{
  "phoneNumber": "+34977385511",
  "phoneType": "PHONEBOOKING"
} 
*/

  String phoneNumber;
  String phoneType;

  HotelDetailModelHotelPhones({
    this.phoneNumber,
    this.phoneType,
  });
  HotelDetailModelHotelPhones.fromJson(Map<String, dynamic> json) {
    phoneNumber = json['phoneNumber']?.toString();
    phoneType = json['phoneType']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['phoneNumber'] = phoneNumber;
    data['phoneType'] = phoneType;
    return data;
  }
}

class HotelDetailModelHotelCity {
/*
{
  "content": "SALOU"
} 
*/

  String content;

  HotelDetailModelHotelCity({
    this.content,
  });
  HotelDetailModelHotelCity.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelAddress {
/*
{
  "content": "Carrer Del Vendrell, 11",
  "street": "Carrer Del Vendrell",
  "number": "11"
} 
*/

  String content;
  String street;
  String number;

  HotelDetailModelHotelAddress({
    this.content,
    this.street,
    this.number,
  });
  HotelDetailModelHotelAddress.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
    street = json['street']?.toString();
    number = json['number']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    data['street'] = street;
    data['number'] = number;
    return data;
  }
}

class HotelDetailModelHotelSegmentsDescription {
/*
{
  "content": "Family hotels "
} 
*/

  String content;

  HotelDetailModelHotelSegmentsDescription({
    this.content,
  });
  HotelDetailModelHotelSegmentsDescription.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelSegments {
/*
{
  "code": 81,
  "description": {
    "content": "Family hotels "
  }
} 
*/

  int code;
  HotelDetailModelHotelSegmentsDescription description;

  HotelDetailModelHotelSegments({
    this.code,
    this.description,
  });
  HotelDetailModelHotelSegments.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toInt();
    description = (json['description'] != null)
        ? HotelDetailModelHotelSegmentsDescription.fromJson(json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelBoardsDescription {
/*
{
  "content": "BED AND BREAKFAST"
} 
*/

  String content;

  HotelDetailModelHotelBoardsDescription({
    this.content,
  });
  HotelDetailModelHotelBoardsDescription.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelBoards {
/*
{
  "code": "BB",
  "description": {
    "content": "BED AND BREAKFAST"
  }
} 
*/

  String code;
  HotelDetailModelHotelBoardsDescription description;

  HotelDetailModelHotelBoards({
    this.code,
    this.description,
  });
  HotelDetailModelHotelBoards.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    description = (json['description'] != null)
        ? HotelDetailModelHotelBoardsDescription.fromJson(json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelAccommodationTypeTypeMultiDescription {
/*
{
  "content": "Hotel"
} 
*/

  String content;

  HotelDetailModelHotelAccommodationTypeTypeMultiDescription({
    this.content,
  });
  HotelDetailModelHotelAccommodationTypeTypeMultiDescription.fromJson(
      Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelAccommodationType {
/*
{
  "code": "HOTEL",
  "typeMultiDescription": {
    "content": "Hotel"
  },
  "typeDescription": "Hotel"
} 
*/

  String code;
  HotelDetailModelHotelAccommodationTypeTypeMultiDescription
      typeMultiDescription;
  String typeDescription;

  HotelDetailModelHotelAccommodationType({
    this.code,
    this.typeMultiDescription,
    this.typeDescription,
  });
  HotelDetailModelHotelAccommodationType.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    typeMultiDescription = (json['typeMultiDescription'] != null)
        ? HotelDetailModelHotelAccommodationTypeTypeMultiDescription.fromJson(
            json['typeMultiDescription'])
        : null;
    typeDescription = json['typeDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (typeMultiDescription != null) {
      data['typeMultiDescription'] = typeMultiDescription.toJson();
    }
    data['typeDescription'] = typeDescription;
    return data;
  }
}

class HotelDetailModelHotelChainDescription {
/*
{
  "content": "OHTELS"
} 
*/

  String content;

  HotelDetailModelHotelChainDescription({
    this.content,
  });
  HotelDetailModelHotelChainDescription.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelChain {
/*
{
  "code": "OHTEL",
  "description": {
    "content": "OHTELS"
  }
} 
*/

  String code;
  HotelDetailModelHotelChainDescription description;

  HotelDetailModelHotelChain({
    this.code,
    this.description,
  });
  HotelDetailModelHotelChain.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    description = (json['description'] != null)
        ? HotelDetailModelHotelChainDescription.fromJson(json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelCategoryGroupDescription {
/*
{
  "content": "Includes 3-star hotels and rural hotels."
} 
*/

  String content;

  HotelDetailModelHotelCategoryGroupDescription({
    this.content,
  });
  HotelDetailModelHotelCategoryGroupDescription.fromJson(
      Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelCategoryGroup {
/*
{
  "code": "GRUPO3",
  "description": {
    "content": "Includes 3-star hotels and rural hotels."
  }
} 
*/

  String code;
  HotelDetailModelHotelCategoryGroupDescription description;

  HotelDetailModelHotelCategoryGroup({
    this.code,
    this.description,
  });
  HotelDetailModelHotelCategoryGroup.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    description = (json['description'] != null)
        ? HotelDetailModelHotelCategoryGroupDescription.fromJson(
            json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelCategoryDescription {
/*
{
  "content": "3 STARS"
} 
*/

  String content;

  HotelDetailModelHotelCategoryDescription({
    this.content,
  });
  HotelDetailModelHotelCategoryDescription.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelCategory {
/*
{
  "code": "3EST",
  "description": {
    "content": "3 STARS"
  }
} 
*/

  String code;
  HotelDetailModelHotelCategoryDescription description;

  HotelDetailModelHotelCategory({
    this.code,
    this.description,
  });
  HotelDetailModelHotelCategory.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    description = (json['description'] != null)
        ? HotelDetailModelHotelCategoryDescription.fromJson(json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelCoordinates {
/*
{
  "longitude": 1.152529,
  "latitude": 41.068407
} 
*/

  double longitude;
  double latitude;

  HotelDetailModelHotelCoordinates({
    this.longitude,
    this.latitude,
  });
  HotelDetailModelHotelCoordinates.fromJson(Map<String, dynamic> json) {
    longitude = json['longitude']?.toDouble();
    latitude = json['latitude']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['longitude'] = longitude;
    data['latitude'] = latitude;
    return data;
  }
}

class HotelDetailModelHotelZoneDescription {
/*
{
  "content": "Salou"
} 
*/

  String content;

  HotelDetailModelHotelZoneDescription({
    this.content,
  });
  HotelDetailModelHotelZoneDescription.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelZone {
/*
{
  "zoneCode": 10,
  "name": "Salou",
  "description": {
    "content": "Salou"
  }
} 
*/

  int zoneCode;
  String name;
  HotelDetailModelHotelZoneDescription description;

  HotelDetailModelHotelZone({
    this.zoneCode,
    this.name,
    this.description,
  });
  HotelDetailModelHotelZone.fromJson(Map<String, dynamic> json) {
    zoneCode = json['zoneCode']?.toInt();
    name = json['name']?.toString();
    description = (json['description'] != null)
        ? HotelDetailModelHotelZoneDescription.fromJson(json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['zoneCode'] = zoneCode;
    data['name'] = name;
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelDestinationName {
/*
{
  "content": "Salou Area / Costa Dorada"
} 
*/

  String content;

  HotelDetailModelHotelDestinationName({
    this.content,
  });
  HotelDetailModelHotelDestinationName.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelDestination {
/*
{
  "code": "SAL",
  "name": {
    "content": "Salou Area / Costa Dorada"
  },
  "countryCode": "ES"
} 
*/

  String code;
  HotelDetailModelHotelDestinationName name;
  String countryCode;

  HotelDetailModelHotelDestination({
    this.code,
    this.name,
    this.countryCode,
  });
  HotelDetailModelHotelDestination.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    name = (json['name'] != null)
        ? HotelDetailModelHotelDestinationName.fromJson(json['name'])
        : null;
    countryCode = json['countryCode']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (name != null) {
      data['name'] = name.toJson();
    }
    data['countryCode'] = countryCode;
    return data;
  }
}

class HotelDetailModelHotelState {
/*
{
  "code": "43",
  "name": "TARRAGONA"
} 
*/

  String code;
  String name;

  HotelDetailModelHotelState({
    this.code,
    this.name,
  });
  HotelDetailModelHotelState.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['name'] = name;
    return data;
  }
}

class HotelDetailModelHotelCountryDescription {
/*
{
  "content": "Spain"
} 
*/

  String content;

  HotelDetailModelHotelCountryDescription({
    this.content,
  });
  HotelDetailModelHotelCountryDescription.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelCountry {
/*
{
  "code": "ES",
  "isoCode": "ES",
  "description": {
    "content": "Spain"
  }
} 
*/

  String code;
  String isoCode;
  HotelDetailModelHotelCountryDescription description;

  HotelDetailModelHotelCountry({
    this.code,
    this.isoCode,
    this.description,
  });
  HotelDetailModelHotelCountry.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    isoCode = json['isoCode']?.toString();
    description = (json['description'] != null)
        ? HotelDetailModelHotelCountryDescription.fromJson(json['description'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['isoCode'] = isoCode;
    if (description != null) {
      data['description'] = description.toJson();
    }
    return data;
  }
}

class HotelDetailModelHotelDescription {
/*
{
  "content": "This hotel is located about 150 metres from the fine sandy beach. The lively centre of Cambrils is approximately 10 km away and can be easily reached by the public bus services. There is a stop for public transport right in front of the hotel. The immediate vicinity offers a diverse range of shopping and entertainment facilities including boutiques, restaurants and bars. This hotel comprises a total of 260 rooms spread over 5 floors. Dining options include a café, a bar and an air-conditioned buffet restaurant with highchairs for infants. The tastefully decorated, cosy rooms come with a balcony and satellite TV."
} 
*/

  String content;

  HotelDetailModelHotelDescription({
    this.content,
  });
  HotelDetailModelHotelDescription.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotelName {
/*
{
  "content": "Ohtels Villa Dorada"
} 
*/

  String content;

  HotelDetailModelHotelName({
    this.content,
  });
  HotelDetailModelHotelName.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    return data;
  }
}

class HotelDetailModelHotel {
/*
{
  "code": 1,
  "name": {
    "content": "Ohtels Villa Dorada"
  },
  "description": {
    "content": "This hotel is located about 150 metres from the fine sandy beach. The lively centre of Cambrils is approximately 10 km away and can be easily reached by the public bus services. There is a stop for public transport right in front of the hotel. The immediate vicinity offers a diverse range of shopping and entertainment facilities including boutiques, restaurants and bars. This hotel comprises a total of 260 rooms spread over 5 floors. Dining options include a café, a bar and an air-conditioned buffet restaurant with highchairs for infants. The tastefully decorated, cosy rooms come with a balcony and satellite TV."
  },
  "country": {
    "code": "ES",
    "isoCode": "ES",
    "description": {
      "content": "Spain"
    }
  },
  "state": {
    "code": "43",
    "name": "TARRAGONA"
  },
  "destination": {
    "code": "SAL",
    "name": {
      "content": "Salou Area / Costa Dorada"
    },
    "countryCode": "ES"
  },
  "zone": {
    "zoneCode": 10,
    "name": "Salou",
    "description": {
      "content": "Salou"
    }
  },
  "coordinates": {
    "longitude": 1.152529,
    "latitude": 41.068407
  },
  "category": {
    "code": "3EST",
    "description": {
      "content": "3 STARS"
    }
  },
  "categoryGroup": {
    "code": "GRUPO3",
    "description": {
      "content": "Includes 3-star hotels and rural hotels."
    }
  },
  "chain": {
    "code": "OHTEL",
    "description": {
      "content": "OHTELS"
    }
  },
  "accommodationType": {
    "code": "HOTEL",
    "typeMultiDescription": {
      "content": "Hotel"
    },
    "typeDescription": "Hotel"
  },
  "boards": [
    {
      "code": "BB",
      "description": {
        "content": "BED AND BREAKFAST"
      }
    }
  ],
  "segments": [
    {
      "code": 81,
      "description": {
        "content": "Family hotels "
      }
    }
  ],
  "address": {
    "content": "Carrer Del Vendrell, 11",
    "street": "Carrer Del Vendrell",
    "number": "11"
  },
  "postalCode": "43840",
  "city": {
    "content": "SALOU"
  },
  "email": "comercial@ohtels.es",
  "license": "HT-000473",
  "phones": [
    {
      "phoneNumber": "+34977385511",
      "phoneType": "PHONEBOOKING"
    }
  ],
  "rooms": [
    {
      "roomCode": "DBL.C4-1",
      "isParentRoom": false,
      "minPax": 1,
      "maxPax": 5,
      "maxAdults": 4,
      "maxChildren": 4,
      "minAdults": 1,
      "description": "DOUBLE CAPACITY 4",
      "type": {
        "code": "DBL",
        "description": {
          "content": "DOUBLE"
        }
      },
      "characteristic": {
        "code": "C4-1",
        "description": {
          "content": "CAPACITY 4"
        }
      }
    }
  ],
  "facilities": [
    {
      "facilityCode": 70,
      "facilityGroupCode": 10,
      "description": {
        "content": "Total number of rooms"
      },
      "order": 1,
      "indYesOrNo": false,
      "number": 260,
      "voucher": false
    }
  ],
  "terminals": [
    {
      "terminalCode": "REU",
      "terminalType": "A",
      "distance": 15,
      "name": {
        "content": "Tarragona, Reus Airport"
      },
      "description": {
        "content": "Airport"
      }
    }
  ],
  "issues": [
    {
      "issueCode": "COVID",
      "issueType": "COVID",
      "description": {
        "content": "As a result of local government measures and guidelines put in place by services providers – including hotels and ancillaries – guests may find that some facilities or services are not available.Please visit https://static-sources.s3-eu-west-1.amazonaws.com/policy/index.html for further information"
      },
      "dateFrom": "2020-05-15",
      "dateTo": "2021-12-31",
      "order": 1,
      "alternative": false
    }
  ],
  "interestPoints": [
    {
      "facilityCode": 40,
      "facilityGroupCode": 100,
      "order": 1,
      "poiName": "Barcelona",
      "distance": "100000"
    }
  ],
  "images": [
    {
      "type": {
        "code": "RES",
        "description": {
          "content": "Restaurant"
        }
      },
      "path": "00/000001/000001a_hb_r_001.jpg",
      "order": 1,
      "visualOrder": 603
    }
  ],
  "wildcards": [
    {
      "roomType": "DBT.ST-2",
      "roomCode": "DBT",
      "characteristicCode": "ST-2",
      "hotelRoomDescription": {
        "content": "MONOPARENTAL 1 ADULT 1 CHILD"
      }
    }
  ],
  "web": "http://www.ohtels.es/",
  "lastUpdate": "2021-07-26",
  "S2C": "4*",
  "ranking": 40
} 
*/

  int code;
  HotelDetailModelHotelName name;
  HotelDetailModelHotelDescription description;
  HotelDetailModelHotelCountry country;
  HotelDetailModelHotelState state;
  HotelDetailModelHotelDestination destination;
  HotelDetailModelHotelZone zone;
  HotelDetailModelHotelCoordinates coordinates;
  HotelDetailModelHotelCategory category;
  HotelDetailModelHotelCategoryGroup categoryGroup;
  HotelDetailModelHotelChain chain;
  HotelDetailModelHotelAccommodationType accommodationType;
  List<HotelDetailModelHotelBoards> boards;
  List<HotelDetailModelHotelSegments> segments;
  HotelDetailModelHotelAddress address;
  String postalCode;
  HotelDetailModelHotelCity city;
  String email;
  String license;
  List<HotelDetailModelHotelPhones> phones;
  List<HotelDetailModelHotelRooms> rooms;
  List<HotelDetailModelHotelFacilities> facilities;
  List<HotelDetailModelHotelTerminals> terminals;
  List<HotelDetailModelHotelIssues> issues;
  List<HotelDetailModelHotelInterestPoints> interestPoints;
  List<HotelDetailModelHotelImages> images;
  List<HotelDetailModelHotelWildcards> wildcards;

  int ranking;

  HotelDetailModelHotel({
    this.code,
    this.name,
    this.description,
    this.country,
    this.state,
    this.destination,
    this.zone,
    this.coordinates,
    this.category,
    this.categoryGroup,
    this.chain,
    this.accommodationType,
    this.boards,
    this.segments,
    this.address,
    this.postalCode,
    this.city,
    this.email,
    this.license,
    this.phones,
    this.rooms,
    this.facilities,
    this.terminals,
    this.issues,
    this.interestPoints,
    this.images,
    this.wildcards,
    this.ranking,
  });
  HotelDetailModelHotel.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toInt();
    name = (json['name'] != null)
        ? HotelDetailModelHotelName.fromJson(json['name'])
        : null;
    description = (json['description'] != null)
        ? HotelDetailModelHotelDescription.fromJson(json['description'])
        : null;
    country = (json['country'] != null)
        ? HotelDetailModelHotelCountry.fromJson(json['country'])
        : null;
    state = (json['state'] != null)
        ? HotelDetailModelHotelState.fromJson(json['state'])
        : null;
    destination = (json['destination'] != null)
        ? HotelDetailModelHotelDestination.fromJson(json['destination'])
        : null;
    zone = (json['zone'] != null)
        ? HotelDetailModelHotelZone.fromJson(json['zone'])
        : null;
    coordinates = (json['coordinates'] != null)
        ? HotelDetailModelHotelCoordinates.fromJson(json['coordinates'])
        : null;
    category = (json['category'] != null)
        ? HotelDetailModelHotelCategory.fromJson(json['category'])
        : null;
    categoryGroup = (json['categoryGroup'] != null)
        ? HotelDetailModelHotelCategoryGroup.fromJson(json['categoryGroup'])
        : null;
    chain = (json['chain'] != null)
        ? HotelDetailModelHotelChain.fromJson(json['chain'])
        : null;
    accommodationType = (json['accommodationType'] != null)
        ? HotelDetailModelHotelAccommodationType.fromJson(
            json['accommodationType'])
        : null;
    if (json['boards'] != null) {
      final v = json['boards'];
      final arr0 = <HotelDetailModelHotelBoards>[];
      v.forEach((v) {
        arr0.add(HotelDetailModelHotelBoards.fromJson(v));
      });
      boards = arr0;
    }
    if (json['segments'] != null) {
      final v = json['segments'];
      final arr0 = <HotelDetailModelHotelSegments>[];
      v.forEach((v) {
        arr0.add(HotelDetailModelHotelSegments.fromJson(v));
      });
      segments = arr0;
    }
    address = (json['address'] != null)
        ? HotelDetailModelHotelAddress.fromJson(json['address'])
        : null;
    postalCode = json['postalCode']?.toString();
    city = (json['city'] != null)
        ? HotelDetailModelHotelCity.fromJson(json['city'])
        : null;
    email = json['email']?.toString();
    license = json['license']?.toString();
    if (json['phones'] != null) {
      final v = json['phones'];
      final arr0 = <HotelDetailModelHotelPhones>[];
      v.forEach((v) {
        arr0.add(HotelDetailModelHotelPhones.fromJson(v));
      });
      phones = arr0;
    }
    if (json['rooms'] != null) {
      final v = json['rooms'];
      final arr0 = <HotelDetailModelHotelRooms>[];
      v.forEach((v) {
        arr0.add(HotelDetailModelHotelRooms.fromJson(v));
      });
      rooms = arr0;
    }
    if (json['facilities'] != null) {
      final v = json['facilities'];
      final arr0 = <HotelDetailModelHotelFacilities>[];
      v.forEach((v) {
        arr0.add(HotelDetailModelHotelFacilities.fromJson(v));
      });
      facilities = arr0;
    }
    if (json['terminals'] != null) {
      final v = json['terminals'];
      final arr0 = <HotelDetailModelHotelTerminals>[];
      v.forEach((v) {
        arr0.add(HotelDetailModelHotelTerminals.fromJson(v));
      });
      terminals = arr0;
    }
    if (json['issues'] != null) {
      final v = json['issues'];
      final arr0 = <HotelDetailModelHotelIssues>[];
      v.forEach((v) {
        arr0.add(HotelDetailModelHotelIssues.fromJson(v));
      });
      issues = arr0;
    }
    if (json['interestPoints'] != null) {
      final v = json['interestPoints'];
      final arr0 = <HotelDetailModelHotelInterestPoints>[];
      v.forEach((v) {
        arr0.add(HotelDetailModelHotelInterestPoints.fromJson(v));
      });
      interestPoints = arr0;
    }
    if (json['images'] != null) {
      final v = json['images'];
      final arr0 = <HotelDetailModelHotelImages>[];
      v.forEach((v) {
        arr0.add(HotelDetailModelHotelImages.fromJson(v));
      });
      images = arr0;
    }
    if (json['wildcards'] != null) {
      final v = json['wildcards'];
      final arr0 = <HotelDetailModelHotelWildcards>[];
      v.forEach((v) {
        arr0.add(HotelDetailModelHotelWildcards.fromJson(v));
      });
      wildcards = arr0;
    }
    ranking = json['ranking']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    if (name != null) {
      data['name'] = name.toJson();
    }
    if (description != null) {
      data['description'] = description.toJson();
    }
    if (country != null) {
      data['country'] = country.toJson();
    }
    if (state != null) {
      data['state'] = state.toJson();
    }
    if (destination != null) {
      data['destination'] = destination.toJson();
    }
    if (zone != null) {
      data['zone'] = zone.toJson();
    }
    if (coordinates != null) {
      data['coordinates'] = coordinates.toJson();
    }
    if (category != null) {
      data['category'] = category.toJson();
    }
    if (categoryGroup != null) {
      data['categoryGroup'] = categoryGroup.toJson();
    }
    if (chain != null) {
      data['chain'] = chain.toJson();
    }
    if (accommodationType != null) {
      data['accommodationType'] = accommodationType.toJson();
    }
    if (boards != null) {
      final v = boards;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['boards'] = arr0;
    }
    if (segments != null) {
      final v = segments;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['segments'] = arr0;
    }
    if (address != null) {
      data['address'] = address.toJson();
    }
    data['postalCode'] = postalCode;
    if (city != null) {
      data['city'] = city.toJson();
    }
    data['email'] = email;
    data['license'] = license;
    if (phones != null) {
      final v = phones;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['phones'] = arr0;
    }
    if (rooms != null) {
      final v = rooms;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['rooms'] = arr0;
    }
    if (facilities != null) {
      final v = facilities;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['facilities'] = arr0;
    }
    if (terminals != null) {
      final v = terminals;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['terminals'] = arr0;
    }
    if (issues != null) {
      final v = issues;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['issues'] = arr0;
    }
    if (interestPoints != null) {
      final v = interestPoints;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['interestPoints'] = arr0;
    }
    if (images != null) {
      final v = images;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['images'] = arr0;
    }
    if (wildcards != null) {
      final v = wildcards;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['wildcards'] = arr0;
    }
    data['ranking'] = ranking;
    return data;
  }
}

class HotelDetailModelAuditData {
  String processTime;
  String timestamp;
  String requestHost;
  String serverId;
  String environment;
  String release;
  String internal;

  HotelDetailModelAuditData({
    this.processTime,
    this.timestamp,
    this.requestHost,
    this.serverId,
    this.environment,
    this.release,
    this.internal,
  });
  HotelDetailModelAuditData.fromJson(Map<String, dynamic> json) {
    processTime = json['processTime']?.toString();
    timestamp = json['timestamp']?.toString();
    requestHost = json['requestHost']?.toString();
    serverId = json['serverId']?.toString();
    environment = json['environment']?.toString();
    release = json['release']?.toString();
    internal = json['internal']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['processTime'] = processTime;
    data['timestamp'] = timestamp;
    data['requestHost'] = requestHost;
    data['serverId'] = serverId;
    data['environment'] = environment;
    data['release'] = release;
    data['internal'] = internal;
    return data;
  }
}

class HotelDetailModel {
  HotelDetailModelAuditData auditData;
  HotelDetailModelHotel hotel;

  HotelDetailModel({
    this.auditData,
    this.hotel,
  });
  HotelDetailModel.fromJson(Map<String, dynamic> json) {
    auditData = (json['auditData'] != null)
        ? HotelDetailModelAuditData.fromJson(json['auditData'])
        : null;
    hotel = (json['hotel'] != null)
        ? HotelDetailModelHotel.fromJson(json['hotel'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (auditData != null) {
      data['auditData'] = auditData.toJson();
    }
    if (hotel != null) {
      data['hotel'] = hotel.toJson();
    }
    return data;
  }
}
